[package]
name = "srl_r"
version = "0.1.0"
authors=["Aidan Bongiorno"]
edition = "2024"

[dependencies]
chrono = "0.4.42"
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"
rusqlite = "0.38.0"
tachyonfx = "0.21.0"
tui-input = "0.14.0"
tui-textarea = "0.7.0"

